name: vibe-app
services:
- name: web
  source_dir: /
  github:
    repo: vibedev-squad-official/vibedev-squad-official
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  env:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  routes:
  - path: /
domains:
- name: staging.vibedevsquad.ai
  type: PRIMARY 